# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-05 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='QUser',
        ),
    ]
