# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-09 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_auto_20170405_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quser',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
