# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-10 02:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_auto_20170409_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 10, 2, 33, 35, 570000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='result',
            field=models.TextField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
