# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-10 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0004_auto_20170410_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('user', models.TextField()),
                ('answer', models.TextField()),
                ('date', models.DateField()),
                ('qid', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
