# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-10 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0005_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
    ]
